baseURL = 'https://helpua.at'
languageCode = 'uk'
title = ''
theme = "hugo-book"
defaultContentLanguage = 'ua'
[languages]
    [languages.en]
        languageName = "ğŸ‡ºğŸ‡¸ English"
        title = "HelpUA"
        weight = 2
        contentDir = 'content.en'
    [languages.ua]
        languageName = "ğŸ‡ºğŸ‡¦ yĞºÑ€Ğ°Ñ—Ğ½ÑÑŒĞºĞ°"
        title = ""
        weight = 1

[params]
    BookTheme = 'auto'
    BookToC = false
    BookSection = 'ĞºÑ€Ğ°Ñ—Ğ½Ğ¸'
    BookLogo = 'logo.jpeg'